services:
  # 1. Background Worker (Fake Web Service to stay on Free Plan)
  - type: web
    name: blostem-worker
    plan: free
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "bash backend/start.sh"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
